name: DisableYT
on:
  workflow_dispatch:
env:
  accountid: ${{ secrets.ACCOUNTID }}
  apitoken: ${{ secrets.APITOKEN }}
  
jobs:
  disableyt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Run check
        run: |
          bash enableyt.sh
